# Generated by Django 5.1.10 on 2025-06-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
